#Resource locations of disallowed actions. Trying to cast one of these will result in a mishap.
actionDenyList = [
	"hextweaks:infusion","hexcasting:explode/fire","hexcasting:explode","hexoverpowered:factor_cut","hexparse:learn_patterns"
]
#Should items fly out of the player's inventory when using Greater Teleport?
greaterTeleportSplatsItems = false
#Should villagers take offense when you flay the mind of their fellow villagers?
villagersOffendedByMindMurder = true
#Resource locations of dimensions you can't Blink or Greater Teleport in.
tpDimDenyList = []
#when false makes player reference iotas behave as normal entity reference iotas
doesTrueNameHaveAmbit = true

[Spells]
	#The maximum number of actions that can be executed in one tick, to avoid hanging the server.
	#Range: > 0
	maxOpCount = 100000
	#The harvest level of the Break Block spell.
	#0 = wood, 1 = stone, 2 = iron, 3 = diamond, 4 = netherite.
	#Range: 0 ~ 4
	opBreakHarvestLevel = 4

["Spell Circles"]
	#The maximum number of slates in a spell circle
	#Range: > 4
	maxSpellCircleLength = 2147483647
	#Resource locations of disallowed actions within circles. Trying to cast one of these in a circle will result in a mishap. For example: hexcasting:get_caster will prevent Mind's Reflection.
	circleActionDenyList = [
	"hextweaks:infusion","hexcasting:explode/fire","hexcasting:explode","hexoverpowered:factor_cut","hexparse:learn_patterns"
]

[Loot]
	#The chance for wandering traders to sell an Ancient Scroll
	#Range: 0.0 ~ 1.0
	traderScrollChance = 0.0

