#can directly parse great spell patterns, without scrolls
#Allowed Values: ALL, DISABLED, BY_SCROLL
ParseGreatSpells = "ALL"
#how comments get parsed into iotas
#ALL: including single & multi line comments;
#MANUAL(default): only `comment_%s`s;
#DISABLED: no comments at all
#Allowed Values: DISABLED, MANUAL, ALL
CommentParsingMode = "MANUAL"
#how indents get parsed into iotas
#ALL(default): coding indents will be auto-converted into `tab_%d`;
#MANUAL: only `tab_%d`s accepted;
#DISABLED: no indents at all
#Allowed Values: DISABLED, MANUAL, ALL
IndentParsingMode = "ALL"
#how many continuous blank lines are allowed in parsed spell; excess ones will be ignored
#Range: > 0
MaxBlankLines = 0
#code indentation add to `tab_N`'s inside nested macros
ExtendIndentInsideMacro = true
#cost to parse single keyword into iota
#Range: 0 ~ 100000
ParserBaseCost = 0
#display colorful nested lists and intro/retros
ShowColorfulNested = true
#how to handle unsupported iota's inner data
#KEEP_NBT(default): save whole NBT as Base64 string;
#SHOW_NBT: output `UNKNOWN(serialized NBT)`;
#SIMPLE: show `UNKNOWN` only
#Allowed Values: SIMPLE, SHOW_NBT, KEEP_NBT
ShowUnknownNBT = "KEEP_NBT"
#randomize property names based on input string
FairPlayPropNames = false

